// <auto-generated />
using System;
using CarBillingApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarBillingApp.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240104191631_firstmigration")]
    partial class firstmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CarBillingApp.API.Entities.BillingEntity", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("VIN")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CustomerInformations")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PurchaseDateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CustomerId", "VIN");

                    b.ToTable("BillingEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
