apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbillingapp
  labels:
    app: carbillingapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carbillingapp
  template:
    metadata:
      labels:
        app: carbillingapp
    spec:
      containers:
      - name: carbillingapp
        image: carwebappcontainerregistry.azurecr.io/carbillingapp:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 300m
            memory: 300Mi
          limits:
            memory: 400Mi
        env:
        - name: PostgreSql
          valueFrom:
            secretKeyRef:
              name: carwebappsettings 
              key: PostgreSql
        - name: CarBillingAppUri
          valueFrom:
            secretKeyRef:
              name: carwebappsettings
              key: CarBillingAppUri
      imagePullSecrets:
        - name: acr-secret
        
