name: L1pipeline_CI

on:
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
  create-and-push-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
      
      - name: Install Docker
        uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      
      - name: Build Images
        run: |
          cd ./CarWebApp
          docker build -t carwebappcontainerregistry.azurecr.io/carwebapp:1.0 .
          cd ..
          cd ./CarBillingApp
          docker build -t carwebappcontainerregistry.azurecr.io/carbillingapp:1.0 .
      
      - name: Login To ACR
        uses: azure/docker-login@v1
        with:
          login-server: carwebappcontainerregistry.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push images TO ACR
        run: |
          docker push carwebappcontainerregistry.azurecr.io/carwebapp:1.0
          docker push carwebappcontainerregistry.azurecr.io/carbillingapp:1.0